# Generated by Django 4.1 on 2024-09-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('location_details', models.CharField(max_length=225)),
                ('industry_type', models.CharField(max_length=225)),
                ('company_description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('resume_upload', models.CharField(max_length=225)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.department')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.log')),
            ],
        ),
        migrations.CreateModel(
            name='job_vaccany',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=225)),
                ('job_description', models.CharField(max_length=225)),
                ('required_skill', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.company')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.log')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.log'),
        ),
        migrations.CreateModel(
            name='application_request',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(max_length=225)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.job_vaccany')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.student')),
            ],
        ),
    ]
