# Generated by Django 4.1 on 2024-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume_upload',
            field=models.FileField(max_length=225, upload_to=''),
        ),
    ]
