# Generated by Django 5.1.6 on 2025-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_student_resume_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('company', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'freelance User Registeration',
            },
        ),
    ]
