# Generated by Django 5.1.6 on 2025-03-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='link.log'),
            preserve_default=False,
        ),
    ]
