# Generated by Django 5.1.6 on 2025-03-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_freelance_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225)),
                ('job_description', models.CharField(max_length=225)),
                ('required_skill', models.CharField(max_length=225)),
                ('expected_duration', models.CharField(max_length=225)),
                ('payment', models.CharField(max_length=225)),
                ('payment_type', models.CharField(choices=[('One Time', 'One Time'), ('Milestone Based', 'Milestone Based'), ('Hourly', 'Hourly')], max_length=225)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.freelance')),
            ],
            options={
                'verbose_name_plural': 'freelance Jobs',
            },
        ),
    ]
