# Generated by Django 5.1.6 on 2025-03-26 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_freelancejobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parttime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('company', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.log')),
            ],
            options={
                'verbose_name_plural': 'Partime User Registeration',
            },
        ),
    ]
