# Generated by Django 5.1.6 on 2025-03-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_parttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParttimeJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225)),
                ('job_description', models.CharField(max_length=225)),
                ('working_hours', models.CharField(max_length=225)),
                ('payment', models.CharField(max_length=225)),
                ('shift_timing', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night'), ('Flexible', 'Flexible')], max_length=225)),
                ('parttime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.parttime')),
            ],
            options={
                'verbose_name_plural': 'Parttime Jobs',
            },
        ),
    ]
