# Generated by Django 5.1.6 on 2025-03-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_parttimejobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.student'),
        ),
    ]
