# Generated by Django 5.1.6 on 2025-03-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_complaint_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
    ]
