# Generated by Django 5.1.6 on 2025-04-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_remove_complaint_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance_application_request',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(max_length=225)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.freelancejobs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.student')),
            ],
        ),
    ]
